

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER exam_jyh IDENTIFIED BY 1234;

GRANT RESOURCE, CONNECT TO exam_jyh; 

ALTER USER exam_jyh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM; 
