

-- 테스트용 테이블 생성 

CREATE TABLE TB_TEST (
	
	TEST_NO NUMBER PRIMARY KEY, 
	TEST_TITLE VARCHAR2(100) NOT NULL, 
	TEST_CONTENT VARCHAR2(500) NOT NULL
	
); 

SELECT * FROM EMPLOYEE;

SELECT JOB_NAME, ROUND(AVG(SALARY),1) SALARY
		FROM EMPLOYEE 
		JOIN JOB USING (JOB_CODE)
		GROUP BY JOB_CODE, JOB_NAME 
		ORDER BY JOB_CODE;


-- 노옹철의 사수 정보
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE J
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE EMP_ID = (SELECT MANAGER_ID FROM EMPLOYEE WHERE EMP_ID = 210 ) ;


SELECT EMP_ID, EMP_NAME 
FROM EMPLOYEE 
WHERE EMP_ID = (SELECT MANAGER_ID FROM EMPLOYEE WHERE EMP_NAME ='노옹철');


SELECT NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, ROUND(AVG(SALARY), 1) SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
GROUP BY DEPT_TITLE, DEPT_CODE
ORDER BY DEPT_CODE;


SELECT * FROM DEPARTMENT;
-- 노옹철 사원과 같은 지역에서 근무하는 직원들 정보 조회 
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY 
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN LOCATION ON (LOCAL_CODE = LOCATION_ID)
JOIN JOB USING (JOB_CODE)
WHERE LOCATION_ID = 
			(SELECT LOCATION_ID 
			 FROM LOCATION 
			 JOIN DEPARTMENT ON (LOCATION_ID = LOCAL_CODE)
			 JOIN EMPLOYEE ON (DEPT_ID = DEPT_CODE)
			 WHERE EMP_NAME = '하이유')	; 



SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME IN (SELECT EMP_NAME 
									FROM EMPLOYEE 
									WHERE JOB_NAME = '부사장'); 



SELECT * FROM JOB;



