

--1 
--학생이름 / 주소지 정렬 : 이름 오름차순 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지 
FROM TB_STUDENT 
ORDER BY STUDENT_NAME ;


--2
--휴학중인 학생들의 이름, 주민번호 나이가 적은 순서대로 
SELECT STUDENT_NAME, STUDENT_SSN  
FROM TB_STUDENT 
ORDER BY STUDENT_SSN DESC ;


--3  
--주소지가 강원도, 경기도 1900년대 학번을 가진 학생이름, 학번, 주소 이름오름차순 
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 거주지주소
FROM TB_STUDENT 
WHERE (SUBSTR(STUDENT_ADDRESS,1,3)LIKE '강원도%' OR SUBSTR(STUDENT_ADDRESS,1,3)LIKE '경기도%')
AND STUDENT_NO NOT LIKE 'A%' 
ORDER BY STUDENT_NAME ; 



--4 법학과 교수중 나이가 많은 사람부터 이름을 확인
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN ; 


--5 2004년 2학기에 'C3118100' 수강한 학생들의 학점 
-- 학점 높은 순으로, 학점이 같으면 학번이 낮은 학생부터 표시 
SELECT STUDENT_NO, POINT
FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO) 
WHERE TERM_NO = '200402' 
ORDER BY POINT DESC, STUDENT_NO ;


--6 학생 번호, 학생이름 학과 이름//학생이름 오름차순 정렬 
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
NATURAL JOIN TB_DEPARTMENT 
ORDER BY STUDENT_NAME; 


--7 과목 이름, 학과이름 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
NATURAL JOIN TB_DEPARTMENT ; 


--8 과목별 교수 이름 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING ( CLASS_NO ) 
JOIN TB_PROFESSOR USING (PROFESSOR_NO )
ORDER BY PROFESSOR_NAME ;


--9 인문사회 계열 과목 교수 이름 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO ) 
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
WHERE CATEGORY = '인문사회'; 


--10 음악학과 학생들의 평점 학번, 학생이름 전체평점 --GRADE STUDENT_NO 
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME; 

 
--11 학번이 A313047 학교에 나오고 있지 않음 지도교수 찾아서 
--학과 이름, 학생이름, 지도교수 이름 
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) 
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047'; 
-- STUDENT랑 PROFESSOR랑 먼저 JOIN시 DEPARTMENT_NO가 너무 많아지는 문제 발생 



--12 2007년에 인간관계론 수강한 학생 
--학생 이름, 수강학기 
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4)='2007' AND CLASS_NAME = '인간관계론'
ORDER BY STUDENT_NAME;
-- WHERE TERM_NO LIKE '2007%'


--13 예체능 계열 과목 중 담당교수를 배정받지 못한 과목 ******
-- 과목 이름, 학과 이름 
SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_CLASS C
FULL JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
FULL JOIN TB_PROFESSOR USING (PROFESSOR_NO)
FULL JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL; 

/*
 * CLASS에는 있으나 PROFESSOR에는 없는 값이 있음 
 * 
 * SELECT CLASS_NAME, DEPARTMENT_NAME
 * FROM TB_CLASS 
 * LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
 * JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
 * WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL; 
 * 
 * */




--14. 서반아어학과 지도교수  *****
--학생이름, 지도교수 이름 지도교수가 없는 학생일 경우 "지도교수 미지정" // 고학번 순으로 
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
FULL JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE S.DEPARTMENT_NO = '020' ;

SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO) 
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;



--15 휴학생이 아닌 학생 중 평점이 4.0이상인 학생 ******
--학번, 이름, 학과이름, 평점 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING AVG(POINT)>=4.0
ORDER BY STUDENT_NO ;


--16 환경조경학과 
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8) "AVG(POINT)"
FROM TB_CLASS 
JOIN TB_GRADE USING(CLASS_NO)
WHERE DEPARTMENT_NO ='034' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY CLASS_NO ;


--17 최경희 학생과 같은 과 학생들의 이름과 주소 

SELECT STUDENT_NAME, STUDENT_ADDRESS 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO =
(SELECT DEPARTMENT_NO FROM TB_DEPARTMENT JOIN TB_STUDENT USING(DEPARTMENT_NO) WHERE STUDENT_NAME ='최경희');


--18 국어국문과에서 총 평점이 가장 높은 학생의 이름 학번 


SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
WHERE POINT IN (SELECT MAX(POINT) 
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '001' GROUP BY STUDENT_NO) ;

SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '001' ;

SELECT MAX(POINT) FROM TB_GRADE;




--19 환경조경학과가 속한 같은 계열 학과들의 학과별 전공과목 평점 
-- 계열 학과명, 전공평점 
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT LEFT JOIN TB_STUDENT USING(DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING(STUDENT_NO) 
WHERE DEPARTMENT_NAME IN
(SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE CATEGORY = '자연과학')
GROUP BY DEPARTMENT_NAME 
;

SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE CATEGORY = '자연과학';






SELECT * FROM TB_CLASS ;
SELECT * FROM TB_GRADE  ;
SELECT * FROM TB_DEPARTMENT ;
SELECT * FROM TB_STUDENT ts ;






