SELECT MEMBER_NO, MEMBER_ID, MEMBER_NICKNAME, 
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') AS ENROLL_DATE 
FROM "MEMBER" 
WHERE MEMBER_DEL_FL = 'N'
AND MEMBER_ID = 'user01' 
AND MEMBER_PW = 'pass01';


SELECT TODO_NO, TODO_TITLE, TODO_MEMO, TODO_DATE
FROM "TODO"
WHERE MEMBER_NO = 1
AND TODO_DEL_FL ='N';

SELECT * FROM TODO t ;