SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
ORDER BY EMP_ID; 

SELECT * FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)			
WHERE EMP_ID = ?; 







SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_TITLE = '인사관리부'; 


SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE SALARY > 5000000;  


SELECT SUM(SALARY) SALARY 
FROM EMPLOYEE 
WHERE DEPT_CODE = 'D1';


SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE EMP_NO = '850607-1313513';

SELECT ROUND(AVG(SALARY),1) 
FROM EMPLOYEE 
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '대리';





























