/* 계정 생성 (관리자 계정으로 접속) */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER kh_jyh IDENTIFIED BY kh1234;

GRANT CONNECT, RESOURCE TO kh_jyh;

ALTER USER kh_jyh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;