/* 계정 생성 (관리자 계정으로 접속) */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER bebegiboo IDENTIFIED BY bebegiboo1234;

GRANT CONNECT, RESOURCE TO bebegiboo;

ALTER USER bebegiboo DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-------------------------------------------------------------------------


SELECT * FROM "MEMBER"; 
SELECT * FROM PRODUCT_TYPE; 



SELECT COUNT(*)
		FROM "MEMBER"
		WHERE MEMBER_DEL_FL = 'N'
		AND MEMBER_ID = 'yoon';

	
	
CREATE TABLE "AUTH_KEY" (
	"KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);	


COMMENT ON COLUMN "AUTH_KEY"."KEY_NO" IS '인증키 번호(PK)';
COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증 이메일';
COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증 번호';
COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

ALTER TABLE "AUTH_KEY"  ADD CONSTRAINT "PK_KEY_NO" PRIMARY KEY (
	"KEY_NO"
);

CREATE SEQUENCE SEQ_KEY_NO NOCACHE;

COMMIT;


SELECT * FROM AUTH_KEY ; 



UPDATE MEMBER SET 
EMAIL = 'vyoonv@gmail.com'
WHERE MEMBER_NO = 4; 

COMMIT;

CREATE TABLE "CERTIFICATION" (
	"C_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)	NOT NULL,
	"MEMBER_NAME" NVARCHAR2(10) NOT NULL, 
	"1365_ID" VARCHAR2(50)	NOT NULL,
	"MEMBER_BIRTH" DATE NOT NULL, 
	"PHONE" VARCHAR2(50) NOT NULL, 
	"ADDRESS" NVARCHAR2(100) NOT NULL, 
	
);	
COMMIT;

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "C_NO_KEY" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_BOARDIMG_TO_IMGNO" FOREIGN KEY (
	"IMG_NO"
)
REFERENCES "BOARD_IMG" (
	"IMG_NO"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_NO" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE CERTIFICATION ADD MEMBER_NO NUMBER NOT NULL;

SELECT * FROM  CERTIFICATION;

ALTER TABLE CERTIFICATION
RENAME COLUMN "1365_ID" TO CERTIFICATION_ID;
---------------------------------------------------------

CREATE TABLE "CERTIFICATION_IMG" (
	"C_IMG_NO"	NUMBER	NOT NULL,
	"C_IMG_PATH"	VARCHAR2(200)	NOT NULL,
	"C_IMG_ORIGINAL_NAME" NVARCHAR2(50) NOT NULL, 
	"C_IMG_RENAME" NVARCHAR2(50)	NOT NULL,
	"C_IMG_ORDER" NUMBER NOT NULL, 
	"C_NO" NUMBER NOT NULL
);	


ALTER TABLE "CERTIFICATION_IMG" ADD CONSTRAINT "C_IMG_KEY" PRIMARY KEY (
	"C_IMG_NO"
);

ALTER TABLE "CERTIFICATION_IMG" ADD CONSTRAINT "FK_C_NO_TO_C_IMG_NO" FOREIGN KEY (
	"C_NO"
)
REFERENCES "CERTIFICATION" (
	"C_NO"
);

COMMIT;



ALTER TABLE "DONATION_RECORD" ADD CONSTRAINT "FK_DO_NO" FOREIGN KEY (
	"DONATOR_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);
ALTER TABLE "DONATION_RECORD" ADD CONSTRAINT "FK_AC_NO" FOREIGN KEY (
	"ACCEPTOR_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);





SELECT * FROM DELIVERY_INFO;
SELECT * FROM DONATION_RECORD;
SELECT * FROM DONATION_PRODUCT;
SELECT * FROM PAYMENT;

CREATE SEQUENCE SEQ_C_NO NOCACHE;
CREATE SEQUENCE SEQ_C_IMG_NO NOCACHE;
CREATE SEQUENCE SEQ_PAY_NO NOCACHE;



SELECT 'SEQ_C_IMG_NO'
FROM user_sequences
WHERE sequence_name = 'SEQ_C_IMG_NO';

DROP SEQUENCE SEQ_C_IMG_NO;

COMMIT;

SELECT * FROM CERTIFICATION_IMG;
SELECT * FROM CERTIFICATION;






INSERT INTO CERTIFICATION 
VALUES(1, 'user01', '유저일', 'user01', 
'1995-05-05', 
'010-1234-1234', '06097^^^서울 강남구 봉은사로 403^^^202호', 4 );



INSERT INTO CERTIFICATION_IMG VALUES(1, '경로1', '파일명1', '변경명1', 1, 1);
INSERT INTO CERTIFICATION_IMG VALUES(2, '경로2', '파일명2', '변경명1', 1, 1);
INSERT INTO CERTIFICATION_IMG VALUES(3, '경로3', '파일명3', '변경명1', 3, 1);

INSERT INTO CERTIFICATION_IMG
(SELECT NEXT_IMG_NO(), '경로1', '원본1', '변경1', 2, 1 FROM DUAL
	UNION
 SELECT NEXT_IMG_NO(), '경로2', '원본2', '변경2', 4, 1 FROM DUAL
 	UNION
 SELECT NEXT_IMG_NO(), '경로3', '원본3', '변경3', 5, 1 FROM DUAL);



SELECT NEXT_IMG_NO FROM DUAL; 



DROP FUNCTION NEXT_IMG_NO; 

COMMIT;



-- SEQ_IMG_NO 시퀀스의 다음 값을 반환하는 함수 생성
CREATE OR REPLACE FUNCTION NEXT_IMG_NO
-- 반환형
RETURN NUMBER
-- 사용할 변수
IS IMG_NO NUMBER; 


BEGIN
	SELECT SEQ_IMG_NO.NEXTVAL
	INTO IMG_NO
	FROM DUAL;
	RETURN IMG_NO;
END;
;

SELECT NEXT_IMG_NO() FROM DUAL;





SELECT *
FROM user_procedures
WHERE object_type = 'FUNCTION';






SELECT SEQUENCE FROM DUAL;



SELECT *
FROM user_sequences;













----------------------------------------------------------------------------------


COMMIT;
SELECT * FROM DONATION_RECORD;
SELECT * FROM DONATION_PRODUCT;
SELECT * FROM DELIVERY_INFO;
SELECT * FROM PRODUCT_TYPE;

SELECT RECORD_NO, RECORD_DATE, DONATOR_NO, ACCEPTOR_NO
FROM DONATION_RECORD
JOIN "MEMBER" ON (DONATOR_NO = MEMBER_NO)
WHERE MEMBER_NO = 4;  


SELECT PRODUCT_NO, PRODUCT_NAME, MEMBER_NO, TYPE_NAME, RECORD_NO
FROM DONATION_PRODUCT
JOIN PRODUCT_TYPE USING(TYPE_NO)
WHERE MEMBER_NO = 4;  

SELECT DONATOR_NAME, PHONE, PHONE2, ADDRESS, PICKUP_DATE, MEMO, MEMBER_NO
FROM DELIVERY_INFO
WHERE MEMBER_NO = 4; 


SELECT * FROM certification_img;


CREATE TABLE "PAYMENT" (
	"PAY_NO"	NUMBER	NOT NULL,
	"PRICE"	NUMBER	NOT NULL,
	"METHOD" NVARCHAR2(50) NOT NULL, 
	"MEMBER_NO" NUMBER	NOT NULL,
	"RECORD_NO" NUMBER NOT NULL
);	


ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAY_NO_KEY" PRIMARY KEY (
	"PAY_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_MEM_NO_TO_MEMBER_NO" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_REC_NO_TO_RECORD_NO" FOREIGN KEY (
	"RECORD_NO"
)
REFERENCES "DONATION_RECORD" (
	"RECORD_NO"
);

COMMIT;

SELECT * FROM PAYMENT;
SELECT * FROM DONATION_RECORD;

INSERT INTO PAYMENT 
VALUES(5, 5000, '신용카드', 4, 5);

SELECT SEQ_PAY_NO.NEXTVAL FROM PAYMENT;


INSERT INTO PAYMENT
		VALUES(SEQ_PAY_NO.NEXTVAL, 5000, '신용카드', 1, )



SELECT PAY_NO, PRICE, METHOD, MEMBER_NO, RECORD_NO
		FROM PAYMENT
		WHERE MEMBER_NO = 4;


SELECT RECORD_NO, TO_CHAR(RECORD_DATE,'YYYY"년"MM"월"DD"일"') "RECORD_DATE" , DONATOR_NO, ACCEPTOR_NO
		FROM DONATION_RECORD
		JOIN "MEMBER" ON (DONATOR_NO = MEMBER_NO)
		WHERE MEMBER_NO = 4;







----------



ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_NAME" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_BIRTH" FOREIGN KEY (
	"MEMBER_BIRTH"
)
REFERENCES "MEMBER" (
	"MEMBER_BIRTH"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_PHONE" FOREIGN KEY (
	"PHONE"
)
REFERENCES "MEMBER" (
	"PHONE"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_ADDRESS" FOREIGN KEY (
	"ADDRESS"
)
REFERENCES "MEMBER" (
	"ADDRESS"
);




-----------------------------------------------------------

 INSERT INTO "CERTIFICATION_IMG" 
 VALUES 
	    

SELECT COUNT(*)
FROM "MEMBER" 
WHERE MEMBER_PW = ;

SELECT * FROM "MEMBER"; 

SELECT * FROM CERTIFICATION ;
SELECT * FROM CERTIFICATION_IMG ;


UPDATE "MEMBER" SET 
EMAIL = 'yyy@gmail.com', 
PHONE = '010-1234-1234', 
MEMBER_PW = '',
ADDRESS = '제주도^^^제주시^^^한라산'
WHERE MEMBER_NO = 4; 








